apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: sandbox-service
build:
  local:
    push: false # 👈 Explicitly forces Skaffold to NEVER try pushing to Docker Hub
  artifacts:
    - image: ai-server
      context: ai
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "**/*.js"

    - image: agent
      context: sandbox/agent
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "**/*.js"

    - image: template
      context: sandbox/template
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "**/*.jsx"
          - "**/*.ts"
          - "**/*.tsx"

    - image: router
      context: sandbox/router
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "**/*.js"

    - image: sandbox
      context: sandbox/server
      docker:
        dockerfile: dockerfile
      sync:
        infer:
          - "**/*.js"

manifests:
  rawYaml:
    - k8s/*.yml # 👈 Uses a wild card so it automatically picks up all manifests cleanly without breaking